export { default as BurgerIcon } from './burger-menu.svg';
export { default as CrossIcon } from './cross.svg';
export { default as ArrowToBottomIcon } from './arrow-to-bottom.svg';
export { default as PlayButtonIcon } from './play-button.svg';
export { default as NavigationIcon } from './navigation.svg';
export { default as BuildingIcon } from './building.svg';
export { default as LeafIcon } from './leaf.svg';
export { default as MapIcon } from './map.svg';
export { default as SendIcon } from './send.svg';
